### ISSUE TITLE
Making the hlist center

### ISSUE THREAD

**Issue by afattahi54** [yamlcss/yaml#47]
Hi,

Can you please let me know how can we make the hlist navigation center?!

Regards,
Alireza Fattahi

**Comment by RiZKiT** [comment]
One solution would be to add the `center` class to your `ym-hlist` element and use the following css

``` css
.ym-hlist.center ul {
 display: inline-block;
 float: none;
}
```
